### ISSUE TITLE
Thoughts on generalizing to CMDB with plugins or standardizing API for others?

### ISSUE THREAD

**Issue by nwmcsween** [tinkerbell/hegel#57]
Looking at various CMDBs and Hegel it seems like it could be supplanted with a CMDB as duplication occurs between both the CMDB and Hegel

**Comment by detiber** [comment]
@nwmcsween I don't necessarily see a CMDB automatically replacing hegel, since there will still be a need for at least a subset of the metadata to be standardized as we look to fully wire up things like cloud-init support during bootstrapping, etc.

I could potentially see some type of a plugin system that would allow Hegel to interact with an external CMDB and translate things between the two, though.

**Comment by nwmcsween** [comment]
Most CMDB's by default don't have a real schema but deal with 'objects' that are defined by the relations and generic data. I really think hegel is superfluous vs. a CMDB or if Hegel was even spun off as a CMDB. Reasoning for this is it's much easier to store data within a CMDB as a source of truth then to have it across n services duplicated.

**Comment by detiber** [comment]
@nwmcsween to give you some context, with cloud-init on the host, and hegel providing standardized metadata (through both a custom format and an AWS compatible format), it is possible to annotate the Hardware definition within Tinkerbell to provide userdata that is available at runtime when bootstrapping using cloud-init.

I'm taking advantage of this as I'm updating cluster-api-provider-tinkerbell to leverage pre-baked images, and the process works surprisingly well. Without hegel (or a similar service providing standardized metadata) the templates/workflows needed become more complicated because that data injection needs to be moved there instead of at runtime.

**Comment by jacobweinstock** [comment]
similar/adjacent discussion here: https://github.com/tinkerbell/tink/issues/253

**Comment by jacobweinstock** [comment]
discussed in triage:

- external integrations (especially netbox) 
- document existing ways to integrate
- Tink data is more transient/install time data than l longer lived source of truth data

**Comment by nwmcsween** [comment]
I disagree with point #3, we do immutable bare metal infra using ipxe and
git that nukes systems on config changes so install data is definitely not
transient.

**Comment by chrisdoherty4** [comment]
Closing the issue as its stale and there isn't an appetite to move toward a CMDB.
