### ISSUE TITLE
Add gRPC endpoint to replace HTTP `/subscribers` endpoint

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/hegel#98]
There's a `subscribers` endpoint exposed from the HTTP server that retrieves gRPC hardware metadata update subscriptions and lists them as JSON. This endpoint doesn't really have anything to do with the HTTP server and ought to be exposed on the gRPC server given its specific to a gRPC endpoint.

**Comment by chrisdoherty4** [comment]
@mmlb @nshalman @displague 

Is the `/subscribers` HTTP endpoint actually used by anyone? It seems like a hack. I'd rather delete it than introduce something in the gRPC API.

**Comment by nshalman** [comment]
I think the subscribers endpoint is documented on our end in troubleshooting guides. It's certainly part of the cacher functionality rather than the tink-server functionality.

I support removal of this stuff in the long term, but we are currently somewhat dependent on that code... @mmlb can hopefully confirm my suspicions.

**Comment by chrisdoherty4** [comment]
Gotcha. I'd love to see this changed to a gRPC endpoint rather than served from the HTTP server given it really has nothing to do with.

**Comment by chrisdoherty4** [comment]
We're introducing a Hegel metadata API and dropping support for Equinix specific APIs which will see the removal of gRPC endpoints. We'll close this issue and await the Hegel API.
